### ISSUE TITLE
Force expansion of the ToolbarLayout

### ISSUE THREAD

**Issue by geecko86** [geecko86/QuickLyric#105]
1- When searching (at least while the Design Library is broken)
2- When displaying a LRC

**Comment by flashlab** [comment]
I guess QL had already support lrc display, nice work~ But I don't know how to make it work, is there an example to make it happen?

**Comment by geecko86** [comment]
It's in the additional sources.

**Comment by flashlab** [comment]
The synchronized lyrics option appears only when the layout is english, maybe the i18n file is broken.

**Comment by geecko86** [comment]
That's correct. Read the ReadMe to find where you can translate the app. It
will appear once that's done.

Poor implementation, but it gets people to work on the translation.

**Comment by flashlab** [comment]
Yeah, It did remind me to update the translation ;)
