### ISSUE TITLE
Fix LRC bug

### ISSUE THREAD

**Issue by geecko86** [geecko86/QuickLyric#113]
The LRCView will sometimes flicker very quickly, to the point where it becomes unreadable.

**Comment by geecko86** [comment]
Possibly fixed?

**Comment by geecko86** [comment]
Closing for now.

**Comment by geecko86** [comment]
Seems to be related to my tweak with the long lines divided into 2.

**Comment by flashlab** [comment]
Is it possible to display all lines and enable scrolling by draging up and down?

**Comment by geecko86** [comment]
@flashlab 
You can do so with the "Show full text" button in the action bar.

https://dl.pushbulletusercontent.com/LoZagpHfprq3Ixl25dw5iZvFY91BFiCb/Screenshot_2015-10-18-11-30-22.png

**Comment by flashlab** [comment]
@geecko86 I mean being able to scroll freely under sync highlight mode. Please consider about this.

**Comment by geecko86** [comment]
@flashlab I'd very much like to hear why you would want this. Are there really moments when you're interested in reading both the current line **and** a line that's much further in the song?
