### ISSUE TITLE
Update the translations strings

### ISSUE THREAD

**Issue by geecko86** [geecko86/QuickLyric#125]
Haven't done that in a while.

This also means manually correcting the arrays that have been altered.

**Comment by geecko86** [comment]
1. Update the email string
2. Make sure the providers array is done right

**Comment by geecko86** [comment]
@beschoenen Would you mind having a look at the dutch translation? :) Let me know if you'd prefer I find someone else. (Thanks!)

https://crowdin.com/project/quicklyric

**Comment by beschoenen** [comment]
No problem, Flemish, right?

**Comment by geecko86** [comment]
Indeed

**Comment by flashlab** [comment]
@geecko86 Chinese string updated.

**Comment by geecko86** [comment]
@flashlab You are the best. Was about to ask you. :+1:

**Comment by beschoenen** [comment]
@geecko86 Flemish is at 88% now, I've made a note of it and I'll continue another time.
