### ISSUE TITLE
Take a closer look at Deezer & PowerAmp

### ISSUE THREAD

**Issue by geecko86** [geecko86/QuickLyric#134]
Sync'd lyrics and broadcasts seem a bit iffy with: 
* Deezer
* Asus music player 
* PowerAmp

They don't broadcast the position field.

Players that don't work at all:
* Apple Music
* saavn
* Pulsar Player
* NetEase
* Pandora

**Comment by flashlab** [comment]
Consider about [RemoteController](http://developer.android.com/reference/android/media/RemoteController.html), many players support it. Have a look at [these](https://github.com/ammar786-1/MusicAnalyzer) project for reference.

**Comment by geecko86** [comment]
Adding a service running in the background and requiring the user to give an additional permission (which only works on KitKat+) are what makes this a last resort. I can easily get in contact with the Deezer dev, I'd rather do that.

**Comment by flashlab** [comment]
Agree.

**Comment by geecko86** [comment]
I should also take a look at Apple Music. 
... I don't know anyone that uses it, though.

**Comment by geecko86** [comment]
A NotificationListener has been implemented after all.

**Comment by beschoenen** [comment]
Apple Music just won't work because it's not sending out system broadcasts, this is why is won't scrobble either.

**Comment by geecko86** [comment]
@beschoenen It's supported via the NotificationListener. There are some very occasional hiccups with the synchronized lyrics but it does work.
