### ISSUE TITLE
Please provide the Beta also over F-Droid

### ISSUE THREAD

**Issue by Wabuo** [geecko86/QuickLyric#141]
Either use your standard repository or create an extra one.

Best regards Wabuo

**Comment by geecko86** [comment]
The preview release (available on www.quicklyric.be), is filled with analytics and advertising.

The whole point (aside from bug reporting) for the Beta is to test the usage metrics and the ads. Analytics and ads are forbidden on F-Droid, so you understand where that leaves us.

**Comment by Wabuo** [comment]
Well if the beta where available on f-droid I would install it and report anything may useful on GitHub.

But there is no way I will install just some .apk untracked from any kind of package manager witch will provide may needed updates.

**Comment by geecko86** [comment]
I forgot to add that as soon as I'm cleared to upload version 2.0 to the Google Play Store, I'll make sure it's available on F-Droid as well. No ETA.
