### ISSUE TITLE
Android studio Error

### ISSUE THREAD

**Issue by edsonreis95** [geecko86/QuickLyric#143]
Hello I wanted to know how I can fix this error

Error:(52, 0) Could not find property 'RELEASE_STORE_PASSWORD' on SigningConfig_Decorated{name=release, storeFile=C:\Users\Edson\Desktop\QuickLyric-master\release.keystore, storePassword=null, keyAlias=null, keyPassword=null, storeType=C:\Users\Edson\Desktop\QuickLyric-master\release.keystore}.
<a href="openFile:C:\Users\Edson\Desktop\QuickLyric-master\QuickLyric\build.gradle">Open File</a>

**Comment by geecko86** [comment]
Which command did you use to build?

My intuition says that you should edit all the stuff that's categorized under "signingConfig"

https://github.com/geecko86/QuickLyric/blob/master/QuickLyric/build.gradle

**Comment by geecko86** [comment]
Closing until you provide more details.
