### ISSUE TITLE
Synchronized lyrics don't show up if the song is already in the db

### ISSUE THREAD

**Issue by geecko86** [geecko86/QuickLyric#145]

**Comment by geecko86** [comment]
It should also be noted that they never work with some players (PowerAmp and Deezer, IIRC).

**Comment by flashlab** [comment]
I think PowerAmp is fine.

**Comment by geecko86** [comment]
@flashlab Care elaborating?

**Comment by flashlab** [comment]
Maybe the latest version is no longer broadcasting, since I didn't update powerAMP long ago.

**Comment by geecko86** [comment]
It does broadcast stuff, but not the "position" field. This means that pausing or moving to the end of a song will cause QL's LRCView to misbehave.

**Comment by geecko86** [comment]
See #134
