### ISSUE TITLE
Add the ability to clear search history 

### ISSUE THREAD

**Issue by pcjl** [geecko86/QuickLyric#148]
You could also add an option in the settings to disable search history if possible.

**Comment by geecko86** [comment]
Duplicate with #109.

**Comment by geecko86** [comment]
But I would be very interested in hearing *why* you think it's a necessary feature. I'm not really convinced atm.

**Comment by pcjl** [comment]
Sometimes, I'll search the lyrics to a song that I'm not listening to at the moment, isn't in my library, and/or I don't listen to often. Once I'm done reading the lyrics sort of as a one-time thing, I don't want the song to appear in my search history. 

Also, the search history popup is not very material, it actually looks like holo (correct me if I'm wrong). It doesn't match the rest of the app. 

Lastly, I don't really like search histories in general (Google Play Store, YouTube, etc.), so having an option to disable it or at least manually clear would be nice.

**Comment by geecko86** [comment]
@pcjl Point taken regarding how it looks. I'll open a new issue.

The problems you report are far from universal. "I don't like search histories" is the most niche argument you can come up with. Adding more and more settings will end up making the app clumbersome and hard to use.

Disabling them completely, for instance, is pointless.

What I *could* do is add a little cross next to each suggestion. Pressing the cross would remove that one search from your history. It would be something you'd have to repeat for each song. How does that sound?

**Comment by pcjl** [comment]
Sure, any sort of way to delete search history is welcome.
