### ISSUE TITLE
Aesthetic improvements

### ISSUE THREAD

**Issue by M2ck** [geecko86/QuickLyric#153]
Could you implement switches everywhere in Settings tab instead of a mix with checkboxes for have a consistent UI and fix header on empty screen that doesn't follow selected color and stay grey (happen only with the news colors). 
![screenshot_2016-04-10-14-34-10](https://cloud.githubusercontent.com/assets/6850125/14411091/196f5c72-ff3f-11e5-954f-2ddbe8853d1f.png)

**Comment by geecko86** [comment]
Very good point about the colors, I wrote it down but forgot to do it. Thanks!

Regarding the mix between checkboxes and switches, right now switches are used to enable synchronized lyrics and the night mode. The switches enable or disable those services. The checkboxes are used for minor options, such as whether or not the lyrics will be saved automatically. That's how I see it, and to me it makes sense. But I completely understand if it's weird for some people. At this point it's still unclear when switch should or shouldn't be used.

I'll make some tests, get some feedback, see what people think about it.

**Comment by M2ck** [comment]
Material Design specs say about checkboxes:
>Checkboxes allow the user to select multiple options from a set.
If you have multiple options appearing in a list, you can preserve space by using checkboxes instead of on/off switches.
**If you have a single option, avoid using a checkbox and use an on/off switch instead.**

And about switches:
>**On/off switches toggle the state of a single settings option.**
The option that the switch controls, as well as the state it’s in, should be made clear from the corresponding inline label. Switches take on the same visual properties of the radio button.
The on/off slide toggle with the text “on” and “off” included within the asset is deprecated. Use the switch shown here instead.

So that's why IMO switches are more appropriates :smiley: 
[Components – Selection controls](https://www.google.com/design/spec/components/selection-controls.html#)
