### ISSUE TITLE
Error In Building Gradle.

### ISSUE THREAD

**Issue by Animeshm77** [geecko86/QuickLyric#169]
Error:(52, 0) Could not find property 'RELEASE_STORE_PASSWORD' on SigningConfig_Decorated{name=release, storeFile=D:\Workspace\downloaded github  projects\QuickLyric-master\release.keystore, storePassword=null, keyAlias=null, keyPassword=null, storeType=D:\Workspace\downloaded github  projects\QuickLyric-master\release.keystore}.
<a href="openFile:D:\Workspace\downloaded github  projects\QuickLyric-master\QuickLyric\build.gradle">Open File</a>

//D:\Workspace\downloaded github  projects\QuickLyric-master is path to the QuickLyric Library.

**Comment by geecko86** [comment]
Read the instructions. You need to edit the build.gradle file.

Don't forget to respect the license.

**Comment by Animeshm77** [comment]
yeah i did that....but still i am getting this error..

Error:Execution failed for task ':QuickLyric:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files (x86)\Java\jdk1.8.0_66\bin\java.exe'' finished with non-zero exit value 1

**Comment by Animeshm77** [comment]
This is my build.gradle file.

apply plugin: 'com.android.application'

repositories {
    mavenCentral()
    jcenter()
    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots/'
    }
    maven {
        url "https://jitpack.io"
    }
}

buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'
    }
}

//noinspection GroovyAssignabilityCheck
android {
    sourceSets {
        main {
            assets.srcDirs = ['assets']
        }
    }

    compileSdkVersion 23
    buildToolsVersion '24'

    defaultConfig {
        applicationId "com.geecko.QuickLyric"
        minSdkVersion 14
        versionCode 65
        versionName "2.0 May Preview 3"
        multiDexEnabled true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }

    signingConfigs {
        release {
            storeFile file('F:\\keystores\\first.jks')
            storePassword 'mypassword'
            keyAlias 'AndroidKey'
            keyPassword 'mypassword'
        }
    }

    buildTypes {
        release {
            shrinkResources true
            minifyEnabled true
            useProguard true
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    lintOptions {
        disable 'InvalidPackage', 'UnusedAttribute', 'GradleDynamicVersion', 'MissingQuantity'
    }
}

dependencies {
    compile 'com.android.support:support-v4:23.+'
    compile 'com.android.support:appcompat-v7:23.+'
    compile 'com.android.support:support-v13:23.+'
    compile 'com.android.support:design:23.+'
    compile 'com.android.support:cardview-v7:23.+'
    compile 'com.android.support:percent:23.+'
    compile 'com.github.medyo:android-about-page:1.0.+'
    compile 'com.balysv:material-ripple:1.0.2'
    compile 'com.android.volley:volley:1.+'
    compile 'org.jraf:android-switch-backport:2.0.1'
    compile 'com.mcxiaoke.viewpagerindicator:library:2.4.1'
    compile 'com.wdullaer:materialdatetimepicker:1.4.2'
    compile 'com.miguelcatalan:materialsearchview:1.4.0'
    compile 'org:jaudiotagger:2.0.3'
    compile 'com.android.support:multidex:1.0.0'
    compile 'org.jsoup:jsoup:1.8.+'
    compile 'ch.acra:acra:4.+'
    compile 'com.zzhoujay.materialcolors:materialcolors:1.0.0'
    compile 'com.squareup.retrofit:retrofit:1.+'
    compile 'com.squareup.okhttp:okhttp:2.+'
    compile 'com.github.geecko86:SpotifyApi:3'
    /* Debug & testing */
    testCompile 'junit:junit:4.12'
    debugCompile 'com.squareup.leakcanary:leakcanary-android:1.4-SNAPSHOT'
    releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.4-SNAPSHOT'
}

**Comment by geecko86** [comment]
Your error is for the debug flavor. SIgning keys are for the the release flavor. It's unrelated, and I'm assuming it's something related to your setup.

Check if your gradle stuff is up to date.

**Comment by Animeshm77** [comment]
Can i use your quicklyric library for my music player app that i will soon
publish on google play store ?

**Comment by geecko86** [comment]
You will get sued by the NMPA if you do that. Unless you sign a deal with them. Lyrics are copyrighted. QuickLyric will soon be back on the play store, but it took us months to make it a legitimate business.

Like I said earlier, you should read the license.
Basically, your app - or at least the lyrics part - needs to be GPLv3 (which means open source), you need to give proper credit to me and you need to send back any changes you make to my code. That is what the license entails.
