### ISSUE TITLE
Save all spotify tracks instead of just saved tracks

### ISSUE THREAD

**Issue by prashantkhurana** [geecko86/QuickLyric#170]
Hi,

A little back story : I use QL to download spotify lyrics from my library and for some reason it was only saving 8 songs always. 
So today I took a look at the code and saw that only the saved tracks are used to fetch lyrics. Not sure how other people use Spotify, but I never save a song. I store playlists for offline use. I imagine everyone doing the same. Downloading the playlist and when you add a song to it, the song gets automatically downloaded. 

So, I am wondering can we download lyrics for all the songs in the users library? It will be a huge number (I know people who have 1000's of songs). Is this feasible to do(api restrictions, too late in the project's timeline etc). If yes, let me know I can do this and submit a PR. Did a dirty version of this, and seems to work. Wanted to ask if this is something you would be interested in or not, before I look more into it. 

Thanks.

**Comment by geecko86** [comment]
Always feel free to send a Pull Request my way (as long as it's not too dirty). Thanks for your help!

**Comment by prashantkhurana** [comment]
Thanks !. Just submitted a PR.
