### ISSUE TITLE
Export all lyrics

### ISSUE THREAD

**Issue by Tony-il-Capo** [geecko86/QuickLyric#181]
Hi
Is there an option to export all the lyrics on device? Like by artist/album?
QuickLyric is a very fast way go get all lyrics for our songs by scanning all songs and grab all possible lyrics, would be nice if we could have them in a plain text file for printing proposes.
I like having them on paper, I print like a mini book by artist.

**Comment by geecko86** [comment]
Out of scope and it would bring additional issues in terms of copyright :)

**Comment by Tony-il-Capo** [comment]
That makes no sense to me as the lyrics are on device already for offline use.
You can print the lyrics to paper for personal study without breaking any copyright law.

Anyway, thanks.
