### ISSUE TITLE
Fix translations

### ISSUE THREAD

**Issue by krt16s** [geecko86/QuickLyric#187]
Lint is throwing up an extra translation, I fix those on my side with:

`echo -e "android { lintOptions { disable 'MissingTranslation'\n\ndisable 'ExtraTranslation' } }" >> build.gradle`

**Comment by geecko86** [comment]
Hey @krt16s,

The last builds appears to be [failing](https://f-droid.org/wiki/page/com.geecko.QuickLyric/lastbuild_124) consistently on F-Droid. This is not something I can fix, correct?

**Comment by krt16s** [comment]
In fact, this is an upstream issue. It works for me when I disable `shrinkResources`. Another option might be to downgrade `com.android.tools.build:gradle:2.3.0` to 2.1.3 according to https://stackoverflow.com/questions/36540676/build-intermediates-res-resources-anzhi-debug-stripped-ap-specified-for-prope/39735179#39735179

**Comment by krt16s** [comment]
Downgrading didnt work for me, so my solution for the current builds is https://gitlab.com/fdroid/fdroiddata/commit/1d01ca11171f1830f47fe9561e050325da2c0976

**Comment by geecko86** [comment]
I meant that's odd - it works fine here. But sure, I guess it's better than nothing. Thanks!

**Comment by geecko86** [comment]
@krt16s We plan on implementing [AcoustID](https://acoustid.biz/), an open source audio fingerprinting service. This requires the use of native code (Chromaprint, also OSS), available [here](https://bitbucket.org/phorton1/chromaprint). How does that work for you guys? Do we somehow need a gradle script that builds it with Cmake? 

Or can F-Droid download the .so files [from here](https://bitbucket.org/phorton1/fpcalc-releases/src/2ae8212839c2ac18c1700dce3efb72acfbf1e618?at=master) via the prebuild options?

**Comment by krt16s** [comment]
Invoking gradle should build them from source, if that tdoesnt work out or is too much work, you could supply a prebuild script that does the building.
