### ISSUE TITLE
Transparent status bar & Navigation Bar on Kitkat

### ISSUE THREAD

**Issue by geecko86** [geecko86/QuickLyric#19]
Right now they're still black. They should instead be transparent and overlay a solid drawable filled with the primary color.

**Comment by Micks29** [comment]
Perhaps this library: [SystemBarTint] (https://github.com/jgilfelt/SystemBarTint) can help you!

**Comment by geecko86** [comment]
Yes, I'd rather use the latter. And indeed

     fitsSystemWindows="true"

works on both KitKat and Lollipop. However, [setting the status bar color via the navigation Drawer](https://developer.android.com/reference/android/support/v4/widget/DrawerLayout.html#setStatusBarBackgroundColor(int)) only works on Lollipop. On Kitkat, the area behind the statusBar stays empty.. I'll try again later.

**Comment by geecko86** [comment]
I'm actually starting to wonder whether that's actually a good idea. Google themselves don't do it. If you can provide an example of an app that does it and where it actually looks good, I'll reopen the issue.
