### ISSUE TITLE
Reduce memory consumption

### ISSUE THREAD

**Issue by geecko86** [geecko86/QuickLyric#192]
App seems to use a lot of memory.

**Comment by svenoaks** [comment]
It doesn't use that much memory, 100mb is not much on current devices. It doesn't constantly increase or anything, seems capped at 108mb. If you put a few icons and an AudioTrack in a single Activity it will use 60mb already as soon as you open it.

**Comment by geecko86** [comment]
For comparison:

* [Lyrically](https://dl2.pushbulletusercontent.com/WBL9kY5y0XaIkseXvYXg4CF3ctcSy37M/Screenshot_20170403-040748.png)
* [QuickLyric](https://dl2.pushbulletusercontent.com/Je1YMZf0CTq5SMeat3eyRr9q09tVEF30/Screenshot_20170403-040755.png)

I just installed Genius and Musixmatch and will watch their memory usage as well. RIght now they're super low but that's probably because it hasn't been too long.

**Comment by svenoaks** [comment]
Google Play Services is 72mb of that

**Comment by geecko86** [comment]
You're probably right. I've been paying too much attention to angry Google Play reviews.
