### ISSUE TITLE
No lyric is displayed

### ISSUE THREAD

**Issue by mahdiG** [geecko86/QuickLyric#193]
Hi. I'm using version 2.0.5 from f-droid. When it detects the song no lyrics are shown.
![screenshot_20170401-135705](https://cloud.githubusercontent.com/assets/4989445/24577529/a57ecf6e-16e4-11e7-9af8-dcdba88f769d.png)

**Comment by geecko86** [comment]
F-Droid is behind on the updates, and it's their fault. I was told in #187 that the next updates should work.

The real issue here is that LyricFind line.
