### ISSUE TITLE
History

### ISSUE THREAD

**Issue by svenoaks** [geecko86/QuickLyric#194]
In the nav drawer add a 'History' entry, which will display the last songs the user listened to in chronological order, with a setting to change the maximum number of entries. If they click on an entry, it will open the lyrics for that song in the main window, like the 'Saved lyrics' do.

**Comment by geecko86** [comment]
An interesting idea :)

As the app picks up songs in the background, it should download lyrics for them (with a setting to turn that off) and the "history" (there's probably a better name) should only contain tracks for which lyrics are _actually_ available.

Worth investigating.

**Comment by geecko86** [comment]
My philosophy is to limit the number of settings to a minimum, though. 
I believe we can pick the max number of entries without making it a setting.

**Comment by geecko86** [comment]
I propose "Recent Tracks" for the name

**Comment by svenoaks** [comment]
I am going to see if I can add a preliminary version this weekend

**Comment by geecko86** [comment]
Hey that'd be great - thanks a lot! :+1: 

I'm guessing you'll spend more time on the back-end than on the UI, but don't hesitate to share your ideas/mockups of how it should look like.

I'm thinking that using the the cached artworks might be a good idea. Right now I'm imagining the end result to be a RecyclerView of Cardviews with the same elevation effect you can see in the Saved Lyrics screen - except each card would contain the artwork, the artist and the title.

Another way to handle it would be to group the tracks by artist or album.

Regarding the max number of entries.. I don't know, 30? Like I said, I think it's best to keep the amount of settings to a minimum.

In my previous comment I mentioned automatically downloading the lyrics on the go - I'm not so sure about that anymore.

**Comment by svenoaks** [comment]
Where is thing that prevents it scrolling up into the album artwork in LocalLyricsFragment as opposed to LyricsFragment. And should probably change the FAB into an up arrow (to scroll to the top, most recent) of the list when it is in RecentTracksFragment. Do we morph it?

Also I using a plain list, not cards, as per material design guidelines as it is homogenous list. Too bad they violate their own guidelines in app store.
