### ISSUE TITLE
typo in german translation

### ISSUE THREAD

**Issue by ds187** [geecko86/QuickLyric#20]
Hi there,

just a small typo report:
in QuickLyric/src/main/res/values-de/strings.xml on line 20 it must be "gespeichert" instead of "gespeichter" and "Songtext" should be written with a capital "S".

It is not really an issue, but i didn't know where else to report.

Greetings ds187 and keep up the good work

**Comment by geecko86** [comment]
You were right to report it. Thank you for your contribution ! Fixed.
