### ISSUE TITLE
Could not connect

### ISSUE THREAD

**Issue by svenoaks** [geecko86/QuickLyric#203]
This seems to be intermittently happening where it will never connect in the Play version and hurting app rating. I have never seen it in the github version, shouldn't it fall through to the crappy lyrics providers if it can't connect to the good ones, whatever is causing the issue with Play providers.

**Comment by geecko86** [comment]
I just fixed it. We're hiring someone to work on the server issues.
If what happened today reproduces, I'll consider importing the other providers.
