### ISSUE TITLE
Behave differently if notification access is disabled

### ISSUE THREAD

**Issue by geecko86** [geecko86/QuickLyric#205]
**Problem:**

If a user changes devices or uninstalls/reinstalls the app for some reason, Google Play will have backed up some of the app data, including whether or not they've seen the intro. However, they still need to go in the system settings and enable notification access. This is especially true since update 2.1 which disabled the broadcast receiver for API 19+.

Another possible scenario is people with super low-spec devices who prefer to keep the background service disabled.

**Possible solutions:**

* DIsplay a warning (where?) that says they need to enable the notification access again
* Re-enable the broadcast receiver while notification access is disabled
* Disable Google's automatic backup

cc @svenoaks

**Comment by geecko86** [comment]
For the warning, I'm thinking either a Snackbar or an additional row in the navigation drawer. Maybe both.

**Comment by svenoaks** [comment]
I would show the slides if notification access is disabled, I believe it prevents them from even using the app, which is as it should be.
