### ISSUE TITLE
[FR] ChangeLog / changes

### ISSUE THREAD

**Issue by ildar** [geecko86/QuickLyric#212]
I no info on new features, even on the Play Market page.
As the workaround I can read [git log](https://github.com/geecko86/QuickLyric/commits/master)

**Comment by geecko86** [comment]
I sometimes add a changelog on the play store and in the app, but not if the only reason I push out a release is to fix a bug that doesn't impact the user (i.e. metrics collection).

I'm probably doing something wrong if you don't see it on the store. Thanks for your feedback.

**Comment by ildar** [comment]
thanks a lot!
