### ISSUE TITLE
Catch LyricsWiki URLs

### ISSUE THREAD

**Issue by ildar** [geecko86/QuickLyric#218]
E.g. if a user or an app wants to open a page like http://lyrics.wikia.com/wiki/John_Newton:Amazing_Grace , it could be opened by the QL.

**Comment by geecko86** [comment]
It was the case a long time ago. 

If someone clicks on a link to Lyricwikia they should go to Lyricwikia.
This has the effect of lowering their page views & their ad revenues.

**Comment by ildar** [comment]
Agreed. Thanks
