### ISSUE TITLE
Improve lyrics catalog

### ISSUE THREAD

**Issue by geecko86** [geecko86/QuickLyric#27]
Some lyrics can't be found. This thread will list songs that QuickLyric couldn't find.
- Please ~~double~~ **TRIPLE** check that you couldn't find a song before reporting such issues with the catalog.
- Please, don't report that "this Madonna song couldn't be found". Work on the assumption that if the music is mainstream, it's in the catalog and you're probably doing something worng. Again, triple check before you report such an issue.
1. This issue thread should be used to report certain **patterns**. For instance, if you've noticed that QuickLyric hasn't been successful in finding lyrics for, say, Metal songs or J-POP or Opera (etc.), you can report that QuickLyric needs to improve support for Metal/J-POP/Opera.
2. If you did find a pattern, you can report it here. _Ideally_ you would also indicate a good source (typically a website or an app) that is very good with that specific genre. For instance: 

> "QuickLyric doesn't work very well with Metal Lyrics, I suggest you have a look at metal-archives.com".

Is a perfect insight.

**Comment by geecko86** [comment]
Added j-lyric.net with #28. Thanks Kevin!

**Comment by geecko86** [comment]
ToDo: add support for :

* plyrics.com
* urbanlyrics.com
* darklyrics.com

(All of which are variants of azlyrics.com)

**Comment by geecko86** [comment]
ToDo: add support for:

* textove.com/ (Bulgarian music)

**Comment by geecko86** [comment]
ToDo: investigate and maybe add support for:

* http://www.uta-net.com/

**Comment by geecko86** [comment]
ToDo: Add support for
(http://www.glamsham.com/music/lyrics/)[glamsham]

**Comment by diegomnds** [comment]
Missing lyric

Europe : Rock the Night

**Comment by geecko86** [comment]
Are you sure? [Here](
https://dl.pushbulletusercontent.com/2F0QVdT0e7GUsTztfFDa9UvgXESWRf1r/Screenshot_2015-04-10-19-39-17.png
).

**Comment by geecko86** [comment]
Are you sure? [Here](https://dl.pushbulletusercontent.com/2F0QVdT0e7GUsTztfFDa9UvgXESWRf1r/Screenshot_2015-04-10-19-39-17.png)

**Comment by diegomnds** [comment]
for me not appear , probably its a bug in my phone, I will erase data from app , thanks for support.

**Comment by galher** [comment]
Love me again - Jihn Newman

**Comment by geecko86** [comment]
@galher: That artist does not exist. "Love me again" by J**o**hn Newman, however, is already in the catalog.

To anyone reading this, please ~~double~~ TRIPLE check before reporting such issues with the catalog.

**Comment by beschoenen** [comment]
As you know the JLyric Provider is slow because it has to load multiple pages. 
There is another big website for native Japanese lyrics, It's called PetitLyrics and this one does have an api. The api is used in a music player app from music.jp. and i did some reverse engineering about a year ago.
Have a look at my documentation here: www.googledrive.com/host/0B9U-HsneqPzXTjlpYVJjOFJFc3M
This api also provides synced lyrics. so that might me a plus for the future (integration with Shuttle?).
I'll try to make a provider for this site in the coming days.

**Comment by Day1721** [comment]
"Grzegorz Hyży & TABB" song's are not exists.

**Comment by dpam182** [comment]
Hi missing lyric here 
Teddy picker- Arctic monkeys 
Thanks

**Comment by geecko86** [comment]
@dpam182: When a music track is THAT popular, please just assume that it must be part of the catalog. Teddy picker is of course no exception.. [Proof](https://dl.pushbulletusercontent.com/5YiSUZbYumMwYCL5gr5kcy1gktajOppj/Screenshot_2015-04-30-20-05-26.png).

**Comment by mrpexan** [comment]
Hi, I'm willing to add lyrics in both Spanish and English, so if there us a way please show me how

**Comment by geecko86** [comment]
@mrpexan: Lyrics aren't added manually. Instead, what needs to be done is adding new lyrics providers (database, APIs, websites, etc.). I'll update the original post. Basically if someone were to report that a certain genre can't be found (e.g. Korean Pop, Metal, Bollywood, etc.) this issue thread can be used to report it. On the other hand, it's not conceivable to work on adding small underground artists whose lyrics you can't even find on Google.

What you CAN do however, is contribute to the Spanish translation. It's 91% complete so you won't have much to do. [Here](https://crowdin.com/project/quicklyric/invite)!

**Comment by geecko86** [comment]
@mrpexan: From what I can see, you've only translated bits of the play store description. The bit that's actually important is the "strings.xml" file.

**Comment by geecko86** [comment]
Investigate Hebrew songs & Asian Music.

**Comment by geecko86** [comment]
PetitLyrics will be implemented

API can be accessed via:

> https://p1.petitlyrics.com/api/GetPetitLyricsData.php

Need to POST the following fields:

* **int** lyricstype: 1 for static, 3 for word for word sync. I'm not sure what 2 is.
* **String** clientAppId:  "p" + 7 random digits
* **int** terminalType: 0


* **int** key_lyricsId: {id in their database}

OR

* **String** key_artist
* **String** key_title


Returns an XML file with metadata + a "LyricsData" field that is encoded in Base64.
