### ISSUE TITLE
too sensitive regarding track names

### ISSUE THREAD

**Issue by anbroid** [geecko86/QuickLyric#30]
If we play an mp3 file, and it's called "Blah_Blah" or "05. Blah Blah" it won't find it, even though if we manually search for "Blah Blah" it finds it. At minimum QuickLyric should strip leading numbers (typically in filenames when ripping tracks). If possible it should replace numbers/symbols with wildcards so it is not so sensitive regarding track names.

**Comment by geecko86** [comment]
It's meant to be this way. It's up to you tag your music properly.

I'm considering suggesting search results when it can't find the song. Would that work for you?

**Comment by anbroid** [comment]
Search results would be great! It could be a setting, for people that would not like this behavior. Thanks!
