### ISSUE TITLE
Allow app name to be translated

### ISSUE THREAD

**Issue by pejakm** [geecko86/QuickLyric#34]
Please allow app name to be localized as well. `app_name` string is available for translation, but still, "QuickLyric" string appears uchanged in Android app list.

**Comment by geecko86** [comment]
QuickLyric is not a word, it's a brand.

Could you argue as to why it's important to translate it?

**Comment by pejakm** [comment]
Serbian language uses both Cyrillic and Latin script, but Cyrillic is preferred. So anything left in Latin script is considered untranslated, and localization is considered incomplete.
We have rules for localising app names, though. If a name is a trademark or a brand, we simply transliterate it. Examples:

Firefox -> Фајерфокс
Coca Cola -> Кока Кола

In other cases we translate or transliterate name, depending on various factors (or the translator's liking). Examples:

Konqueror -> К-освајач ("освајач" means "konqueror")
Dolphin -> Делфин ("делфин" means "dolphin")

In case of QuickLyric, I choose to translate it ("Брзи стих", meaning "quick lyric"), not knowing it was a brand (sorry), but I'll transliterate it to "Квик лирик", which is basically how we pronounce "quick lyric", so your brand name will be retained.

**Comment by geecko86** [comment]
I see.

Seems like as the project leader I was able to force a translation:
http://puu.sh/gm74U.png

Thanks for reporting the issue!

**Comment by pejakm** [comment]
Thank you for taking my arguments into consideration. :)
