### ISSUE TITLE
Issues with action bar

### ISSUE THREAD

**Issue by Micks29** [geecko86/QuickLyric#51]
When I select text, action bar become white and empty, see screenshot:
<a href="http://www.hostingpics.net/viewer.php?id=433370Screenshot20150323140026.png"><img src="http://img11.hostingpics.net/thumbs/mini_433370Screenshot20150323140026.png" alt="Upload images" /></a>
In Lyrics saved tab, action bar color is weird and seems miss delete button, see screenshot:
<a href="http://www.hostingpics.net/viewer.php?id=774184Screenshot20150323140040.png"><img src="http://img11.hostingpics.net/thumbs/mini_774184Screenshot20150323140040.png" alt="Upload images" /></a> 

These issues happen with the dark theme too.
I'm on latest CM11 nightly (Android Kitkat 4.4.4)

**Comment by geecko86** [comment]
Yup, it's been reported to me via email. Doesn't happen on Lollipop.
Probably related to the shadow. 

FYI it's a staged rollout, only 50% of users have access to 1.7

**Comment by geecko86** [comment]
Alright, after investigating the issue I came to the conclusion that it was caused by commit 0227813.

It seems like they changed a couple of stuff in the styles attributes.. Would be nice to give us a warning. Anyway, I just fixed it.

I can't reproduce your issue with the delete button, though. Let me know if it still happens.

**Comment by Micks29** [comment]
Thanks, fixed except for delete button in Lyrics saved tab.

**Comment by Micks29** [comment]
I've just noticed this issue happen in portrait mode only, take a look on screenshots below:

![screenshot_2015-03-26-21-04-08](https://cloud.githubusercontent.com/assets/6850125/6855931/b6d99c62-d3fc-11e4-9cb4-bd3529f3f01e.png)
Portrait mode

![screenshot_2015-03-26-21-04-18](https://cloud.githubusercontent.com/assets/6850125/6855944/d2aee6ea-d3fc-11e4-8a18-6f05c30f9b3b.png)
Landscape mode

So I think the issue happen on devices with a small screen like my Galaxy S2 (4.3").
Hope that help you for find a fix!
