### ISSUE TITLE
Reload lyrics button's animation

### ISSUE THREAD

**Issue by ChadGray** [geecko86/QuickLyric#56]
The shadow rotates with update/reload button c:

**Comment by geecko86** [comment]
Which version of the app do you have? It's been fixed already.

**Comment by ChadGray** [comment]
from f-droid

**Comment by geecko86** [comment]
They've stopped updating the app, I'll ask them why.

**Comment by geecko86** [comment]
It could also be that you're using the old package.

Here: https://f-droid.org/repository/browse/?fdfilter=QuickLyric&fdid=com.geecko.QuickLyric

Not https://f-droid.org/repository/browse/?fdfilter=QuickLyric&fdid=be.geecko.QuickLyric
