### ISSUE TITLE
Translation Japanese provider is wrong

### ISSUE THREAD

**Issue by beschoenen** [geecko86/QuickLyric#69]
The translation for J-Lyric in the select box is wrong. Currently it's "Japanese (ひらがな)" or "Japanese (hiragana)". Hiragana is one of the writing systems used in Japanese. 
I think that you want is "日本語" which means "Japanese" in Japanese.

**Comment by geecko86** [comment]
That's what it's supposed to be. In the future, there will hopefully be a provider for japanese lyrics in Romaji (it's been requested), hence the "Hiragana" in parentheses.

**Comment by beschoenen** [comment]
It might still be a good idea to change it. For one to indicate the lyrics are in native Japanese and also because JLyric doesn't provide lyrics in just hiragana, but in all Japanese writing systems.

**Comment by geecko86** [comment]
Fair point.. What do you suggest?

**Comment by beschoenen** [comment]
I would suggest "Japanese (日本語)" for providers in native Japanese and "Japanese (Rōmaji)" for providers with romanised Japanese.

**Comment by geecko86** [comment]
@beschoenen "Nihongo" means japanese, as I'm sure you know. No point in writing "japanese (japanese)", is there? Can't you think of a word for "native" that would fit Kanjis, Hiragana, Katakana,..? Cheers

**Comment by beschoenen** [comment]
Okay. Maybe "Japanese (漢字と仮名)" which stands for "kanji and kana".

**Comment by geecko86** [comment]
Let's ask @naofum :)

What do you think naofum? Would "漢字と仮名" do the trick?

**Comment by naofum** [comment]
HI!!!
Usually, speaking of Japanese, Kanji, Hiragana and katakana are mixed. 
For the native , it is OK in "Japanese". 
If only Hiragana, only katakana or only Romaji, it could be nice
to write "Japanese (Hiragana)", "Japanese (Katakana)" or "Japanese (Romaji)".

**Comment by geecko86** [comment]
Mh.. Yes now that I think about it, it makes a lot more sense that way. Thank you! :-)

I'll remove the "(ひらがな)" in all languages.
