### ISSUE TITLE
bugs and suggestions

### ISSUE THREAD

**Issue by flashlab** [geecko86/QuickLyric#73]
Hi, here are some perhaps 'bugs' and suggestions:
1. In `DOWNLOADTHREAD.java` line 149, maybe `lyrics = download(params[0], artist, title);` is needed
2. the album image will resize and push the title and aritist area to the right when I refresh under the same track.
3. Maybe option for whether download album image is much better, because sometime it's not necessory and will make the fetching process very slow.
4. I will give you more idea when I have some.
Anyway, thanks for your work~

**Comment by geecko86** [comment]
1. The way a switch statement works is that because there is no break; in case 3, it will continue executing the next instructions. The next instruction happens to be download(params[0],artist, title), so there is nothing to change.

2. This has been fixed, I haven't pushed the changes yet. This only happened when reading the artworks from id3 tags AFAIK.

3. So, making it possible to have no image at all? Is that what you mean? The AsyncTask that takes care of the album artworks starts after the lyrics have been downloaded, so it doesn't slow anything down.

Thanks for your insights, I appreciate your kind words too. :)

**Comment by flashlab** [comment]
You've kidding me, you responded so quick~
1. the issuse came from when I compile the latest version, Null pointer error throw out in line 156 when I click **Jlyric** searching result list
2. Waiting for your next commit~~
3. I don't konw how the art pic fetch task works, just hope we have this option
4. I've submit the Chinese translation, hope you can take it

**Comment by geecko86** [comment]
Ah yes! I saw your translation. I'm super grateful. Thank you very much.

I'll let you know when I push my changes. Search is currently being revamped, which explains your bug. This will also be fixed.

**Comment by geecko86** [comment]
I just pushed a lot of changes.

**Comment by flashlab** [comment]
@geecko86 Cheers! I can‘t wait to share a bug with you ;)
In `LyricsViewFragment` line 403 I think it should be more like `.setMessage(Html.fromHtml(String.format(String.valueOf(getString(R.string.why_popup_text)), title, artist)))`
Once I find sth, I will let you know the very first time ~

**Comment by geecko86** [comment]
Humm, why? If title or artist contain HTML tags (who knows what modern
music can be like sometimes), your code will cause issues.

**Comment by flashlab** [comment]
Hi, @geecko86 . When I click on the search result item, the program return to the lyricsview without download and refresh text. Any tips?

**Comment by geecko86** [comment]
All the time with all the providers? What was the search query? Is your code up to date?

**Comment by flashlab** [comment]
Yes, the apk file was generated from src code of May 2nd version. the result list seems fine, but I can't get the lyric text from any item. I'll dig deeper latter.

**Comment by geecko86** [comment]
There was a bug in some cases with Lyric.wikia.com, I just fixed it. I doubt it would have happened 100% of the time though.

**Comment by flashlab** [comment]
I'm pretty sure it happens on any result. [This](https://drive.google.com/file/d/0BzA1sf0Y5BxySU0xWjVRbjgxLUE/view?usp=sharing) was compiled from version `07f7f00` on my pc, you may have a try if you like. And I'll keep looking around the code to figure out why.

**Comment by flashlab** [comment]
@geecko86 I made a short video to explain my problem → [ql.gif](https://drive.google.com/file/d/0BzA1sf0Y5BxyZ2pjZDJUVEozRGM/view?usp=sharing)
The apk file(ver. **1.8**) came from google play was running on **Chrome ARC**,  with same performance on my phone.

**Comment by geecko86** [comment]
Weird. I can't reproduce the problem here. Do you have all the default settings? Auto-refresh might have something to do with this.

Since you have some dev skills, I would suggest debugging starting from the "onActivityResult" callback (MainActivity.java).

**Comment by geecko86** [comment]
This might be a bit of a stretch but.. since you live in Wuhan, China.. I would investigate the possibility that you're having connection issues. I don't believe this is directly related to the code, but more to your configuration (China governement blocking stuff, maybe your use of a VPN, etc.). Check out the stacktrace with "adb logcat" to see if you're getting some IOExceptions.

**Comment by flashlab** [comment]
I'm sure it has nothing about the net;) The same issue arised with a VPN. I made a break point in "onActivityResult", but nothing return after I click on the result. Here is the debug level logcat:
>05-05 12:36:28.953    5527-5527/com.geecko.QuickLyric I/ActivityManager﹕ Timeline: Activity_idle id: android.os.BinderProxy@424252e0 time:20659969
05-05 12:36:29.403    1063-1136/? I/ActivityManager﹕ Timeline: Activity_windows_visible id: ActivityRecord{425ed838 u0 com.geecko.QuickLyric/.MainActivity t36} time:20660419

Any ideas?

**Comment by geecko86** [comment]
Looks unrelated. Are you running KitKat on your phone?

**Comment by flashlab** [comment]
@geecko86 Yes,android 4.4.2.

**Comment by geecko86** [comment]
It's been fixed now. Apparently Android 4.x doesn't call onActivityResult from activities that have "singletask" enabled.

**Comment by flashlab** [comment]
Yes! It works. And I create a new provider "Baidu", which mainly support Chinese music, and "viewlyrics", which is friendly to oriental languages. Since I don't konw how to use "fork", Can I just send you the java files? It's very simple, modified from other provider's code.

**Comment by geecko86** [comment]
I'd strongly encourage you to learn how to use git. It's much easier than it looks. You can use tools like [TreeSource](https://www.sourcetreeapp.com/) to make things easier.

Worst case scenario, create a [gist](https://gist.github.com/) and paste your code. Maybe create a new issue to make things clearer.

And thanks for contributing!

**Comment by flashlab** [comment]
@geecko86 Check the files [here](https://gist.github.com/flashlab/aa67360b7cad1bc28a97), it works for me ;)
And will it possible to turn Genius and Lyricswiki into an option? Cause they are in the prior position in search process with pool connect speed and bad result in China.

**Comment by geecko86** [comment]
Could you open a new issue with that, like I said? Using 1 thread for all your questions and contributions is a bad way of doing things. Or.. just make a nice pull request. That would be infinitely better.

You should also know that I won't be touching the project for a while (exams are coming up). Big changes like reorganizing the providers will definitely have to wait..

**Comment by flashlab** [comment]
@geecko86 All right, I'll start a new issue. And wish youget a nice grades!
