### ISSUE TITLE
Make it possible to edit tags

### ISSUE THREAD

**Issue by geecko86** [geecko86/QuickLyric#75]
Artist and title, perhaps lyrics

**Comment by beschoenen** [comment]
Automatically save lyrics to ID3 perhaps.

**Comment by flashlab** [comment]
Under most circumstance, the edit button was hidden, bugs or limitation?

**Comment by geecko86** [comment]
Look at the code, I don't have access to a computer right now.

In theory, it should show up as long as Android finds an audio file with
the requested artist & title on the external storage.
