### ISSUE TITLE
New provider (Baidu and viewlyrics) request

### ISSUE THREAD

**Issue by flashlab** [geecko86/QuickLyric#82]
I create a new provider "Baidu", which mainly support Chinese music, and "viewlyrics", which is friendly to oriental languages. source files are [here](https://gist.github.com/flashlab/aa67360b7cad1bc28a97). Besides, you may probably download the corresponding mp3 file on the bottom.

**Comment by geecko86** [comment]
For future reference: https://github.com/PedroHLC/ViewLyricsOpenSearcher

**Comment by geecko86** [comment]
I don't speak Chinese, so I can't work on supporting Baidu. Closing for now.
