### ISSUE TITLE
Wrong Button Shadow

### ISSUE THREAD

**Issue by mamins1376** [geecko86/QuickLyric#95]
i use right-to-left direction for my phone, it seems to be the reason.
the shadow is at right side, instead of left.

![wrong-button-shadow](https://cloud.githubusercontent.com/assets/10245985/8777260/382ea89c-2f0c-11e5-828d-9381e273d9a8.png)

**Comment by geecko86** [comment]
Can you download QuickLyric 2.0 beta and let me know if the problem is fixed?

http://goo.gl/forms/98hSOLsQyO

If you downloaded the app from F-Droid, you will have to uninstall it first.

**Comment by mamins1376** [comment]
yep, it fixed and it is now in it's place. thanks :D
i want to translate it to Persian; how to do it?

**Comment by geecko86** [comment]
crowdin.com/project/quicklyric

Thanks!

**Comment by geecko86** [comment]
I just added Persian to the languages. Sorry about that.

**Comment by mamins1376** [comment]
Translation Complated :dancers:
